### ISSUE TITLE
Disable console.log() in docker branch

### ISSUE THREAD

**Issue by chrisli30** [bodhiproject/bodhi-api#33]
Since we poll default qtumd account "" address which is not registered on the chain, api keeps printing out "Address does not exist" error. Let's turn off all console output in production. Ideally we would set up config and use one environment like logger:off to do this, but for now let's just remove console.log from responses in index.js.

Error: Address does not exist
api_1    |     at checkStatus (/usr/src/bodhi/bodhi-api/node_modules/qweb3/src/httpprovider.js:77:15)
api_1    |     at <anonymous>
api_1    |     at process._tickCallback (internal/process/next_tick.js:160:7)

**Comment by chrisli30** [comment]
0a6f1e9190bd07f4dd46fc1cd593a943f497aa0d
